version: '3.8'

services:
  app:
    build:
      context: .
    container_name: pr-reviewer-service
    ports:
      - "8080:8080"
    depends_on:
      storage:
        condition: service_healthy

    environment:
      DB_HOST: storage
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: TestTask
    restart: on-failure

  storage:
    container_name: storage
    image: postgres:18-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: TestTask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d TestTask -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: